[tool.black]
line-length = 119
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 119

[tool.mypy]
python_version = 3.9
ignore_missing_imports = true