class BaseHelpButtonTexts:
    own_help = "Інше (написати власноруч)"
    skip_org = "Пропустити"
    regions_left = "⬅"
    regions_right = "➡"
    own_city = "Ввести власноруч"
    back_to_main_menu = "🏡 В головне меню"

    callback_data_own_help = "own_help"
    callback_data_prefix_for_help = "h_"
    callback_data_prefix_payments = "p_"
    callback_data_prefix_transfer = "t_"
    callback_data_prefix_region = "r_"
    callback_data_prefix_change_region = "region_menu_"
    callback_data_prefix_city = "c_"
    callback_data_skip_org = "skip"
    callback_data_own_city = "own_city"
